name: Testing Only

on:
  issue_comment:
    types: [created, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Find out what to check out
        id: get_pr_head
        run: |
          echo "PR_HEAD=$(curl -s ${{ github.event.issue.pull_request.url }} | jq '.head.sha' | xargs echo)"
          echo "PR_HEAD=$(curl -s ${{ github.event.issue.pull_request.url }} | jq '.head.sha' | xargs echo)" >> $GITHUB_OUTPUT

      # Check out repository under $GITHUB_WORKSPACE
      - name: Check this out!
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_pr_head.outputs.PR_HEAD }}

      - run: cat README.md
      - name: Check what we have
        run: |
          git status
          git show --stat
